//23K2001 Muzammil Q3
#include<iostream>
using namespace std;
class darazpersonData{
protected:
string l_name, f_name, address, city, state,zip, phone;
public:
darazpersonData(string f_name,string l_name, string address,string city,string state,string zip,string phone) : f_name(f_name),l_name(l_name),address(address),city(city),state(state),zip(zip),phone(phone) {}
void setFname(string f) { f_name = f; }
void setLname(string l) { l_name = l; }
void setAddress(string a) { address = a; }
void setCity(string c) { city = c; }
void setState(string s) { state = s; }
void setZip(string z) { zip = z; }
void setPhone(string p) { phone = p; }
string getFname() { return f_name; }
string getLname(){ return l_name; }
string getAddress() { return address; }
string getCity() { return city; }
string getState() { return state;}
string getZip() { return zip; }
string getPhone() { return phone; }
};
class customerData : public darazpersonData{
protected:
int num, loyalty;
public:
customerData(string f_name,string l_name, string address,string city,string state,string zip,string phone,int points) : darazpersonData(f_name,l_name,address,city,state,zip,phone)
{
do{
if(points>=0){
loyalty = points;
break;
}
else{
cout<<"Loyalty points cannot be negative, input again: ";
cin>>points;
}
}while(1);
int *p = &num;
num = (int)p;
}
void setLoyalty(int n) { loyalty = n; }
int getLoyalty() { return loyalty; }
int getNum(){ return num;}
};
class loyaltyProgram : public customerData{
public:
loyaltyProgram(string f_name,string l_name, string address,string city,string state,string zip,string phone,int points) : customerData(f_name,l_name,address,city,state,zip,phone,points){}
void addPoints(int ps){
if(ps<0)
cout<<"Points cannot be <0 !!!"<<endl;
else{
setLoyalty(getLoyalty()+ps);
cout<<ps<<" points added for customer#"<<getNum()<<" "<<endl;
displayPoints();
}
}
void redeemPoints(int ps){
if(ps<0)
cout<<"Points cannot be <0 !!!"<<endl;
else if(ps>getLoyalty())
cout<<"Not enough points for this customer."<<endl;
else{
setLoyalty(getLoyalty()-ps);
cout<<ps<<" points redeemed for customer#"<<getNum()<<" "<<endl;
displayPoints();
}
}
void displayPoints(){
cout<<"Current Loyalty points available for Customer#"<<getNum()<<" ";
cout<<getFname()<<" "<<getLname()<<" -> "<<getLoyalty()<<endl;
}
void displayData(){
cout<<"\nName: "<<getFname()<<" "<<getLname()<<endl;
cout<<"Address: "<<getAddress()<<", "<<getCity()<<", "<<getState()<<endl;
cout<<"Zip: "<<getZip()<<" Phone#: "<<getPhone()<<endl;
cout<<"Customer# (generated by Daraz.pk): "<<getNum()<<endl;
displayPoints();
}
};
int main()
{
cout<<"23K2001 - Muzammil\n\n"<<endl;
loyaltyProgram me("Muzammil","Siddiqui","Block 7","Karachi","Pakistan","75300","+923061234",-1);
int ch;
cout<<"\n\t\t***WELCOME TO DARAZ.PK***"<<endl;
do {
cout<<"\n1. Add new customer to loyalty program";
cout<<"\n2. Add loyalty points for purchases - (for main() object)";
cout<<"\n3. Redeem loyalty points for discounts - (for main() object)";
cout<<"\n4. Display total loyalty points for a customer - (for main() object)";
cout<<"\n5. Exit";
cout<<"\nEnter your choice: ";
cin>>ch;
switch(ch) {
case 1: {
string
fname,lname,address,city,state,zip,phone;
int points;
cout<<"Input the following data: "<<endl;
cout<<"1st name: ";
cin>>fname;
cout<<"Last name: ";
cin>>lname;
cout<<"Address: ";
cin>>address;
cout<<"City: ";
cin>>city;
cout<<"State: ";
cin>>state;
cout<<"Zip: ";
cin>>zip;
cout<<"Phone: ";
cin>>phone;
cout<<"Loyalty points: ";
cin>>points;
loyaltyProgram
stranger(fname,lname,address,city,state,zip,phone,points);
cout<<"New customer added successfully!"<<endl;
stranger.displayData();
break;
}
case 2: {
cout<<"How many points to add: ";
int x;
cin>>x;
me.addPoints(x);
break;
}
case 3: {
cout<<"How many points to redeem: ";
int x;
cin>>x;
me.redeemPoints(x);
break;
}
case 4: {
me.displayPoints();
break;
}
case 5:
return 0;
default:
cout<<"Invalid choice, try again!";
}
} while(ch != 5);
return 0;
}
